package:
  name: yamllint
  version: 1.33.0
  description: adrienverge/yamllint image.
  target-architecture:
    - all
  copyright:
    - license: MIT
      paths:
        - "*"
  dependencies:
    runtime:
      - python3

environment:
  contents:
    repositories:
      - https://dl-cdn.alpinelinux.org/alpine/v3.19/main
      - https://dl-cdn.alpinelinux.org/alpine/v3.19/community
    packages:
      - apk-tools
      - busybox
      - python3
      - py3-pip

pipeline:
  - name: Update registries
    runs: apk update
  - name: Install yamllint
    runs: |
      python3 -m venv /opt/yamllint
      . /opt/yamllint/bin/activate
      pip install yamllint==${{package.version}}
      mkdir -p ${{targets.destdir}}/usr/lib/python3.11
      cp -R /usr/lib/python3.11/site-packages/ ${{targets.destdir}}/usr/lib/python3.11/
      mkdir -p ${{targets.destdir}}/usr/bin
      cp /opt/yamllint/bin/yamllint ${{targets.destdir}}/usr/bin/yamllint
