[env]

[tools]
apko = "0.19.1"
dockle = "0.4.14"
ekdo = "0.1.0"
grype = "0.82.1"
melange = "0.12.1"
shellbits = "0.2.0"
snyk = "1.1293.1"
trivy = "0.56.2"

[plugins]
ekdo = 'https://github.com/mecha-hq/asdf-ekdo'
shellbits = 'https://github.com/mecha-hq/asdf-shellbits'
