
[env]

[tools]
  apko = "0.29.10"
  dockle = "0.4.15"
  gh = "2.75.0"
  grype = "0.96.1"
  hugo = "0.144.2"
  melange = "0.30.3"
  snyk = "1.1298.1"
  trivy = "0.64.1"
  updatecli = "0.104.0"
  yq = "4.47.1"
  ytt = "0.52.0"
