
[settings]
  lockfile = true

[tools]
  act = "0.2.87"
  apko = "1.2.2"
  dockle = "0.4.15"
  gh = "2.89.0"
  grype = "0.111.0"
  hugo = "0.144.2"
  melange = "0.48.2"
  snyk = "1.1304.0"
  taplo = "0.10.0"
  trivy = "0.69.3"
  updatecli = "0.117.0"
  yq = "4.52.5"
  ytt = "0.53.2"
