[env]

[tools]
  # dev
  yq = "4.47.1"
  ytt = "0.52.0"

  # ci
  gh = "2.75.0"
  updatecli = "0.104.0"

  # build
  apko = "0.29.9"
  melange = "0.29.7"

  # scan
  dockle = "0.4.15"
  grype = "0.96.0"
  snyk = "1.1298.0"
  trivy = "0.64.1"

  # pages
  hugo = "0.144.2"
