name: Build and Scan Tool
description: Build an OCI image for a given tool on a given arch and scan it, producing reports. Optionally publish both the image and the reports on GitHub.
inputs:
  melange_signing_key:
    description: "The signing key for Melange."
    required: true
  mise_version:
    description: "The version of mise to install."
    default: "2024.11.4"
    required: false
  snyk_org:
    description: "The Snyk organization to use for scanning."
    required: true
  snyk_token:
    description: "The Snyk token to use for scanning."
    required: true
  tool_arch:
    description: "The arch to build the tool or collection for. default is amd64,arm64."
    default: "amd64,arm64"
    required: false
  tool_name:
    description: "The name of the tool or collection to build."
    required: true
  tool_publish:
    description: "Whether to publish the container images and manifests. default is false."
    default: "false"
    required: false
runs:
  using: "composite"
  steps:
    # - name: Harden Runner
    #   uses: step-security/harden-runner@v2
    #   with:
    #     egress-policy: audit

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      with:
        platforms: arm64

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Install mise
      uses: jdx/mise-action@v2
      with:
        version: ${{ inputs.mise_version }}

    - name: Activate mise
      shell: sh
      run: echo 'eval "$(~/.local/share/mise/bin/mise activate bash)"' >> ~/.bashrc

    - name: Dump the signing key
      shell: sh
      run: if [ ! -f "melange.rsa" ]; then echo "${{ inputs.melange_signing_key }}" > melange.rsa; fi

    - name: Build ${{ inputs.tool_name }}
      uses: ./.github/actions/tool
      with:
        name: ${{ inputs.tool_name }}
        arch: ${{ inputs.tool_arch }}
        publish: ${{ inputs.tool_publish }}
      env:
        SNYK_ORG: ${{ inputs.snyk_org }}
        SNYK_TOKEN: ${{ inputs.snyk_token }}

    - name: Remove the signing key
      shell: sh
      run: shred -v -z -u -n 5 melange.rsa
      if: always()
