name: Build and Scan Image
description: Build an OCI image for a given image on a given arch and scan it, producing reports. Optionally publish both the image and the reports on GitHub.
inputs:
  container_registry_password:
    description: "The password for the Container registry."
    required: true
  melange_signing_key:
    description: "The signing key for Melange."
    required: true
  mise_version:
    description: "The version of mise to install."
    default: "2025.4.0"
    required: false
  snyk_org:
    description: "The Snyk organization to use for scanning."
    required: true
  snyk_token:
    description: "The Snyk token to use for scanning."
    required: true
  image_arch:
    description: "The arch to build the image for. default is amd64,arm64."
    default: "amd64,arm64"
    required: false
  image_name:
    description: "The name of the image to build."
    required: true
  publish:
    description: "Whether to publish the built artifacts(images, manifests, gh-pages, etc). default is false."
    default: "false"
    required: false
  site_base_url:
    description: "The base URL for the site."
    default: "https://mecha-hq.github.io/images"
    required: false
runs:
  using: "composite"
  steps:
    # Validate the inputs

    - name: validate inputs.name
      shell: sh
      run: make validate-name IMAGE=${{ inputs.image_name }}

    - name: validate inputs.arch
      shell: sh
      run: make validate-arch ARCH=${{ inputs.image_arch }}

    # Prepare the environment

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      with:
        platforms: arm64

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Install mise
      uses: jdx/mise-action@v2
      with:
        version: ${{ inputs.mise_version }}

    - name: Activate mise
      shell: sh
      run: echo 'eval "$(~/.local/share/mise/bin/mise activate bash)"' >> ~/.bashrc

    - name: Dump the signing key
      shell: sh
      run: if [ ! -f "melange.rsa" ]; then echo "${{ inputs.melange_signing_key }}" > melange.rsa; fi

    - name: Determine image version
      shell: sh
      run: echo IMAGE_VERSION=$(make image-version IMAGE=${{ inputs.image_name }}) >> ${GITHUB_ENV}

    # Prepare and publish the Container Image

    - name: Build APK package
      shell: sh
      run: make melange ARCH=${{ inputs.image_arch }} IMAGE=${{ inputs.image_name }}

    - name: Create OCI Image
      shell: sh
      run: make apko ARCH=${{ inputs.image_arch }} IMAGE=${{ inputs.image_name }}

    - name: Load OCI images
      shell: sh
      run: make docker-load IMAGE=${{ inputs.image_name }} VERSION="${IMAGE_VERSION}"

    - name: Login to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: mecha-hq
        password: ${{ inputs.container_registry_password }}

    - name: Upload OCI images
      shell: sh
      run: make docker-push ARCH=${{ inputs.image_arch }} IMAGE=${{ inputs.image_name }} VERSION="${IMAGE_VERSION}"
      if: ${{ inputs.publish == 'true' }}

    # Scan the Container Image

    - name: Scan OCI images with Dockle
      shell: sh
      run: make dockle ARCH=${{ inputs.image_arch }} IMAGE=${{ inputs.image_name }} VERSION="${IMAGE_VERSION}"

    - name: Scan OCI images with Grype
      shell: sh
      run: make grype ARCH=${{ inputs.image_arch }} IMAGE=${{ inputs.image_name }} VERSION="${IMAGE_VERSION}"

    # - name: Scan OCI images with Trivy
    #   shell: sh
    #   run: make trivy ARCH=${{ inputs.image_arch }} IMAGE=${{ inputs.image_name }} VERSION="${IMAGE_VERSION}"

    # - name: Scan OCI images with Snyk
    #   shell: sh
    #   run: make snyk ARCH=${{ inputs.image_arch }} IMAGE=${{ inputs.image_name }} VERSION="${IMAGE_VERSION}"
    #   env:
    #     SNYK_ORG: ${{ inputs.snyk_org }}
    #     SNYK_TOKEN: ${{ inputs.snyk_token }}

    # Prepare and publish Github Pages

    - name: Setup GitHub Pages
      uses: actions/configure-pages@v5

    - name: Prepare GitHub Pages
      shell: sh
      run: make prepare-gh-pages IMAGE="${{ inputs.image_name }}" VERSION="${{ env.IMAGE_VERSION }}"

    - name: Build with Hugo
      shell: sh
      env:
        HUGO_CACHEDIR: ${{ runner.temp }}/hugo_cache
        HUGO_ENVIRONMENT: production
        TZ: Europe/Rome
      run: |
        hugo \
        --gc \
        --minify \
        --baseURL "${{ inputs.site_base_url }}/" \
        --source pages/

    - name: Push the generated pages content to the repository
      shell: sh
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "GitHub Actions"
        git add pages/content
        git commit -m "Update GitHub Pages content with ${{ inputs.image_name }} ${IMAGE_VERSION} data."
        git push
      if: ${{ inputs.publish == 'true' }}

    - name: Upload GitHub Pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./pages/public
      if: ${{ inputs.publish == 'true' }}

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
      if: ${{ inputs.publish == 'true' }}

    # Draft and Publish the release

    - name: Draft GitHub Release
      shell: sh
      run: make draft-gh-release IMAGE=${{ inputs.image_name }} VERSION="${IMAGE_VERSION}"

    - name: Publish GitHub Release
      shell: sh
      run: make publish-gh-release IMAGE=${{ inputs.image_name }} VERSION="${IMAGE_VERSION}"
      if: ${{ inputs.publish == 'true' }}

    # Cleanup the environment

    - name: Remove the signing key
      shell: sh
      run: shred -v -z -u -n 5 melange.rsa
      if: always()
