#! diff.yml

#@ load("fragments.lib.yml","updatecli_jobs", "step_harden_runner", "step_checkout", "step_install_mise", "step_activate_mise", "step_make")

name: Diff

permissions:
  contents: read

"on":
  workflow_dispatch:
  pull_request:

jobs:
  diff:
    runs-on: ubuntu-24.04
    steps:
      -  #@ step_harden_runner()
      -  #@ step_checkout()
      -  #@ step_install_mise()
      -  #@ step_activate_mise()
      -  #@ step_make("generate-config")
      - name: Verify no changes are made
        shell: sh
        run: git diff --exit-code
