#! fragments.lib.yml

#@ def jobs_build(image, runs_on):
runs-on: #@ runs_on
permissions:
  contents: write
  id-token: write
  packages: write
  pages: write
steps:
  - name: Harden Runner
    uses: step-security/harden-runner@v2
    with:
      egress-policy: audit
  - name: Checkout code
    uses: actions/checkout@v4
    with:
      submodules: recursive
      fetch-depth: 0
  - name: Build image
    uses: ./.github/actions/image
    with:
      container_registry_password: ${{ secrets.CI_TOKEN }}
      melange_signing_key: ${{ secrets.MELANGE_SIGNING_KEY }}
      snyk_org: ${{ secrets.SNYK_ORG }}
      snyk_token: ${{ secrets.SNYK_TOKEN }}
      image_name: #@ image
      publish: ${{ github.ref == 'refs/heads/main' && 'true' || 'false' }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#@ end

#@ def on(image):
workflow_dispatch:
push:
  branches:
    - main
  paths:
    #! tool-specific paths
    -  #@ ".github/workflows/" + image + ".yaml"
    -  #@ "tools/"+ image + "/**"
    #! common paths
    - ".github/actions/**"
    - ".mise.*"
    - Makefile
    - melange.rsa.pub
    - "scripts/**"
    - "pages/**"
    - "!pages/content"
pull_request:
  paths:
    #! tool-specific paths
    -  #@ ".github/workflows/" + image + ".yaml"
    -  #@ "tools/"+ image + "/**"
    #! common paths
    - ".github/actions/**"
    - ".mise.*"
    - Makefile
    - melange.rsa.pub
    - "scripts/**"
    - "pages/**"
    - "!pages/content"
#@ end

#@ def updatecli_on(freq):
workflow_dispatch: {}
schedule:
  - cron: #@ "0 */%s * * *" % freq
#@ end

#@ def updatecli_permissions():
contents: "write"
pull-requests: "write"
#@ end

#@ def updatecli_jobs(scope):
updatecli:
  runs-on: "ubuntu-24.04"
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Updatecli in the runner
      uses: updatecli/updatecli-action@v2
      with:
        version: v0.103.1

    - name: Run Updatecli for dependencies in Dry Run mode
      run: #@ "updatecli diff --config ./updatecli/updatecli.d/%s --values updatecli/values.yaml --values updatecli/values.ci.yaml" % scope
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Run Updatecli for dependencies
      run: #@ "updatecli apply --config ./updatecli/updatecli.d/%s --values updatecli/values.yaml --values updatecli/values.ci.yaml" % scope
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
#@ end
