#! scans.yml

name: Scans

#@ load("fragments.lib.yml", "step_harden_runner", "step_checkout", "step_scan_image", "step_generate_pages", "step_publish_gh_release")

"on":
  schedule:
    - cron: "0 0 * * *" #! Runs every day at 00:00 UTC

jobs:
  setup:
    runs-on: ubuntu-24.04
    outputs:
      tools: ${{ steps.get-tools.outputs.tools }}
    steps:
      -  #@ step_harden_runner()
      -  #@ step_checkout()
      - name: Get tools list
        id: get-tools
        run: |
          tools=$(ls -1 tools/ | jq -R -s -c 'split("\n")[:-1]')
          echo "tools=$tools" >> $GITHUB_OUTPUT
  scan:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      id-token: write
      pages: write
    strategy:
      matrix:
        tool: ${{ fromJson(needs.setup.outputs.tools) }}
      fail-fast: false
    steps:
      -  #@ step_harden_runner()
      -  #@ step_checkout()
      -  #@ step_scan_image("${{ matrix.tool }}")
      -  #@ step_generate_pages("${{ matrix.tool }}")
