#! jsonlint.yml

name: Jsonlint

#@ load("fragments.lib.yml", "jobs_build", "tool_on")

#@yaml/text-templated-strings
"on": #@ tool_on("jsonlint")

jobs:
  build: #@ jobs_build("jsonlint", "ubuntu-24.04")
