#! updatecli-rebuild.yml

#@ load("fragments.lib.yml", "step_harden_runner", "step_checkout", "step_get_tools_list", "step_compute_image_version", "step_build_image", "step_scan_image", "step_generate_pages")

name: Updatecli Rebuild
"on":
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  setup:
    if: startsWith(github.head_ref, 'updatecli_main_')
    runs-on: ubuntu-24.04
    outputs:
      tools: ${{ steps.get-tools.outputs.tools }}
    steps:
      -  #@ step_harden_runner()
      -  #@ step_checkout()
      -  #@ step_get_tools_list()
  scan:
    needs: setup
    if: startsWith(github.head_ref, 'updatecli_main_')
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      id-token: write
      pages: write
    strategy:
      matrix:
        tool: ${{ fromJson(needs.setup.outputs.tools) }}
      fail-fast: false
    steps:
      -  #@ step_harden_runner()
      -  #@ step_checkout()
      -  #@ step_compute_image_version("${{ matrix.tool }}")
      -  #@ step_build_image("${{ matrix.tool }}", "false")
      -  #@ step_scan_image("${{ matrix.tool }}", "false")
      -  #@ step_generate_pages("${{ matrix.tool }}", "false")
