#! updatecli-rebuild.yml

#@ load("fragments.lib.yml", "step_harden_runner", "step_checkout", "step_get_tools_list", "step_compute_image_version", "step_build_image", "step_scan_image", "step_generate_pages")

name: Updatecli Rebuild
"on":
  workflow_dispatch:
  pull_request:
    branches:
      - main
env:
  REBUILD_TOOL: checkmake #! the tool used to test all the steps work
jobs:
  rebuild:
    if: ${{
      startsWith(github.head_ref, 'updatecli_main_') &&
      (
      contains(github.event.pull_request.title, 'melange') ||
      contains(github.event.pull_request.title, 'apko')
      )
      }}
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      -  #@ step_harden_runner()
      -  #@ step_checkout()
      -  #@ step_compute_image_version("${{ env.REBUILD_TOOL }}")
      -  #@ step_build_image("${{ env.REBUILD_TOOL }}", "false")
      -  #@ step_scan_image("${{ env.REBUILD_TOOL }}", "false", "false")
      -  #@ step_generate_pages("${{ env.REBUILD_TOOL }}", "false")
  rescan:
    if: ${{
      startsWith(github.head_ref, 'updatecli_main_') &&
      (
      contains(github.event.pull_request.title, 'dockle') ||
      contains(github.event.pull_request.title, 'grype') ||
      contains(github.event.pull_request.title, 'snyk') ||
      contains(github.event.pull_request.title, 'trivy')
      )
      }}
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      -  #@ step_harden_runner()
      -  #@ step_checkout()
      -  #@ step_compute_image_version("${{ env.REBUILD_TOOL }}")
      -  #@ step_scan_image("${{ env.REBUILD_TOOL }}", "true", "false")
      -  #@ step_generate_pages("${{ env.REBUILD_TOOL }}", "false")
  regen_pages:
    if: ${{
      startsWith(github.head_ref, 'updatecli_main_') &&
      (
      contains(github.event.pull_request.title, 'hugo')
      )
      }}
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      -  #@ step_harden_runner()
      -  #@ step_checkout()
      -  #@ step_generate_pages("the static site")
