package:
  name: jsonlint
  version: "1.6.3"
  epoch: 0
  description: zaach/jsonlint image.
  copyright:
    - license: MIT
      paths:
        - "*"
  dependencies:
    runtime:
      - nodejs-current

environment:
  contents:
    repositories:
      - https://dl-cdn.alpinelinux.org/alpine/v3.19/main
      - https://dl-cdn.alpinelinux.org/alpine/v3.19/community
    packages:
      - apk-tools
      - busybox
      - nodejs-current
      - npm

pipeline:
  - name: Update registries
    runs: apk update
  - name: Build NPM Base Image
    runs: npm install jsonlint@${{package.version}} -g --prefix "${{targets.destdir}}"
