package:
  name: checkmake
  version: 0.2.2
  epoch: 0
  description: mrtazz/checkmake image.
  copyright:
    - license: MIT
      paths:
        - "*"
  dependencies:
    runtime: []

environment:
  contents:
    repositories:
      - https://dl-cdn.alpinelinux.org/alpine/v3.22/main
      - https://dl-cdn.alpinelinux.org/alpine/v3.22/community
    packages:
      - apk-tools
      - busybox
      - go

pipeline:
  - name: Update registries
    runs: apk update
  - name: Install checkmake
    uses: go/install
    with:
      package: github.com/mrtazz/checkmake/cmd/checkmake
      version: ${{package.version}}
      tests: "false"
