name: Build and Scan Tool
description: Build an OCI image for a given tool on a given arch and scan it, producing reports. Optionally publish both the image and the reports on GitHub.
inputs:
  name:
    description: "The name of the tool or collection to build."
    required: true
  arch:
    description: "The arch to build the tool or collection for. default is amd64."
    default: "amd64"
    required: false
  publish:
    description: "Whether to publish the container images and manifests. default is false."
    default: "false"
    required: false
runs:
  using: "composite"
  steps:
    - name: validate inputs.name
      shell: sh
      run: make validate-name IMAGE=${{ inputs.name }}

    - name: validate inputs.arch
      shell: sh
      run: make validate-arch ARCH=${{ inputs.arch }}

    - name: Determine tool version
      shell: sh
      run: echo TOOL_VERSION=$(make tool-version IMAGE=${{ inputs.name }}) >> ${GITHUB_ENV}

    - name: Build APK package
      shell: sh
      run: make melange ARCH=${{ inputs.arch }} IMAGE=${{ inputs.name }}

    - name: Create OCI Image
      shell: sh
      run: make apko ARCH=${{ inputs.arch }} IMAGE=${{ inputs.name }} VERSION="${TOOL_VERSION}"

    - name: Load OCI images
      shell: sh
      run: make docker-load IMAGE=${{ inputs.name }} VERSION="${TOOL_VERSION}"

    - name: Scan OCI images
      shell: sh
      run: make scan ARCH=${{ inputs.arch }} IMAGE=${{ inputs.name }} VERSION="${TOOL_VERSION}"

    - name: Render the scans
      shell: sh
      run: make render ARCH=${{ inputs.arch }} IMAGE=${{ inputs.name }} VERSION="${TOOL_VERSION}"

    - name: Upload OCI images
      shell: sh
      run: make docker-push ARCH=${{ inputs.arch }} IMAGE=${{ inputs.name }} VERSION="${TOOL_VERSION}"
      if: ${{ inputs.publish }} == 'true'

    - name: Upload reports artifact
      uses: actions/upload-artifact@v4
      with:
        path: dist/${{ inputs.name }}/reports
      if: ${{ inputs.publish }} == 'true'

    - name: Setup Pages
      uses: actions/configure-pages@v4
      if: ${{ inputs.publish }} == 'true'

    - name: Upload pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: dist/${{ inputs.name }}/renders
      if: ${{ inputs.publish }} == 'true'

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
      if: ${{ inputs.publish }} == 'true'
