package:
  name: jsonlint
  version: 1.6.3
  description: zaach/jsonlint image.
  target-architecture:
    - all
  copyright:
    - license: MIT
      paths:
        - "*"
  dependencies:
    runtime:
      - nodejs-current

environment:
  contents:
    repositories:
      - https://dl-cdn.alpinelinux.org/alpine/v3.18/main
      - https://dl-cdn.alpinelinux.org/alpine/v3.18/community
    packages:
      - alpine-baselayout-data
      - apk-tools
      - ca-certificates-bundle
      - busybox
      - nodejs-current
      - npm

pipeline:
  - name: Update registries
    runs: apk update
  - name: Build NPM Base Image
    runs: npm install jsonlint@1.6.3 -g --prefix "${{targets.destdir}}"
