package:
  name: yamlfmt
  version: 0.17.2
  epoch: 0
  cpe:
    vendor: "google"
    product: "yamlfmt"
  description: google/yamlfmt image.
  copyright:
    - license: MIT
      paths:
        - "*"
  dependencies:
    runtime: []
  checks: {}

capabilities:
  add: []
  drop: []

update:
  enabled: false

environment:
  contents:
    repositories:
      - https://dl-cdn.alpinelinux.org/alpine/v3.23/main
      - https://dl-cdn.alpinelinux.org/alpine/v3.23/community
    packages:
      - apk-tools
      - go

pipeline:
  - name: Update registries
    runs: apk update
  - name: Install yamlfmt
    uses: go/install
    with:
      package: github.com/google/yamlfmt/cmd/yamlfmt
      version: v${{package.version}}
