package:
  name: yamlfmt
  version: 0.13.0
  description: google/yamlfmt image.
  target-architecture:
    - all
  copyright:
    - license: MIT
      paths:
        - "*"
  dependencies:
    runtime: []
environment:
  contents:
    repositories:
      - https://dl-cdn.alpinelinux.org/alpine/v3.19/main
      - https://dl-cdn.alpinelinux.org/alpine/v3.19/community
    packages:
      - apk-tools
      - go
pipeline:
  - name: Update registries
    runs: apk update
  - name: Install yamlfmt
    uses: go/install
    with:
      package: github.com/google/yamlfmt/cmd/yamlfmt
      version: v${{package.version}}
