---
name: Checkmake

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      # checkmake-specific paths
      - ".github/workflows/checkmake.yaml"
      - "tools/checkmake/**"
      # common paths
      - ".github/actions/**"
      - ".mise.*"
      - Makefile
      - melange.rsa.pub
      - scripts/**"
  pull_request:
    paths:
      # checkmake-specific paths
      - ".github/workflows/checkmake.yaml"
      - "tools/checkmake/**"
      # common paths
      - ".github/actions/**"
      - ".mise.*"
      - Makefile
      - melange.rsa.pub
      - scripts/**"

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      pages: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build image
        uses: ./.github/actions/image
        with:
          container_registry_password: ${{ secrets.CI_TOKEN }}
          melange_signing_key: ${{ secrets.MELANGE_SIGNING_KEY }}
          mise_version: 2024.11.4
          snyk_org: ${{ secrets.SNYK_ORG }}
          snyk_token: ${{ secrets.SNYK_TOKEN }}
          image_arch: amd64,arm64
          image_name: checkmake
          image_publish: ${{ github.ref == 'refs/heads/main' && 'true' || 'false' }}
