---
name: Checkmake Pushes on Main

on:
  push:
    branches:
      - main
    paths:
      - ".github/actions/**"
      - ".github/workflows/checkmake-*.yaml"
      - ".mise.*"
      - "tools/checkmake/**"
      - Makefile
      - melange.rsa.pub
      - scripts/**"

jobs:
  publish:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Dump the signing key
        run: if [ ! -f "melange.rsa" ]; then echo "${{ secrets.MELANGE_SIGNING_KEY }}" > melange.rsa; fi

      - name: Install os deps
        run: sudo apt update -y && sudo apt install -y bubblewrap

      - name: Install mise
        uses: jdx/mise-action@v2
        with:
          version: 2024.11.4

      - name: Setup mise shims
        uses: ./.github/actions/mise-shims

      - name: Test build of new tool version
        uses: ./.github/actions/tool
        with:
          name: checkmake
          arch: amd64
          publish: false

      - name: Remove the signing key
        run: shred -v -z -u -n 5 melange.rsa
        if: always()
