---
name: Checkmake Pull Requests

on:
  workflow_dispatch:
  pull_request:
    paths:
      - ".github/actions/**"
      - ".github/workflows/checkmake-*.yaml"
      - ".mise.*"
      - "tools/checkmake/**"
      - Makefile
      - melange.rsa.pub
      - scripts/**"

jobs:
  build:
    runs-on: ${{ matrix.runner.name }}
    strategy:
      fail-fast: false
      matrix:
        runner:
          - name: ubuntu-24.04
            arch: ["amd64"]
    services:
      docker:
        image: docker:dind
        options: --privileged --shm-size=2g
    steps:
      # - name: Harden Runner
      #   uses: step-security/harden-runner@v2
      #   with:
      #     egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Dump the signing key
        run: if [ ! -f "melange.rsa" ]; then echo "${{ secrets.MELANGE_SIGNING_KEY }}" > melange.rsa; fi

      - name: Install mise
        uses: jdx/mise-action@v2
        with:
          version: 2024.11.4

      - name: Activate mise
        shell: sh
        run: echo 'eval "$(~/.local/share/mise/bin/mise activate bash)"' >> ~/.bashrc

      - name: Test build of new tool version
        uses: ./.github/actions/tool
        with:
          name: checkmake
          arch: ${{ matrix.runner.arch }}
          publish: "false"
        env:
          SNYK_ORG: ${{ secrets.SNYK_ORG }}
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Remove the signing key
        run: shred -v -z -u -n 5 melange.rsa
        if: always()
