---
name: Checkmake Pull Requests

on:
  workflow_dispatch:
  pull_request:
    paths:
      # checkmake-specific paths
      - ".github/workflows/checkmake-*.yaml"
      - "tools/checkmake/**"
      # common paths
      - ".github/actions/**"
      - ".mise.*"
      - Makefile
      - melange.rsa.pub
      - scripts/**"

jobs:
  build:
    runs-on: ubuntu-24.04
    services:
      docker:
        image: docker:dind
        options: --privileged --shm-size=2g
    steps:
      - name: Full Tool Build
        uses: ./.github/actions/tool-full
        with:
          tool_name: checkmake
          tool_arch: amd64,arm64
          tool_publish: "false"
          mise_version: 2024.11.4
        env:
          SNYK_ORG: ${{ secrets.SNYK_ORG }}
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
