---
name: Checkmake Pull Requests

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "tools/checkmake/**"
      - ".github/workflows/checkmake-*.yaml"
      - Makefile
      - melange.rsa.pub

jobs:
  checkmake-qa:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install mise
        uses: ./.github/actions/mise
      - name: Test new tool version
        uses: ./.github/actions/tool
        with:
          tool: checkmake
          publish: false
