---
name: Checkmake Pushes on Main

on:
  push:
    branches:
      - main
    paths:
      - "tools/checkmake/**"
      - ".github/workflows/checkmake-*.yaml"
      - Makefile
      - melange.rsa.pub

jobs:
  publish:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Dump the signing key
        run: echo "${{ secrets.MELANGE_SIGNING_KEY }}" > melange.rsa
      - name: Install os deps
        run: apt install -y bubblewrap
      - name: Install mise
        uses: ./.github/actions/mise
      - name: Publish new tool version
        uses: ./.github/actions/tool
        with:
          name: checkmake
          arch: amd64
          publish: false
      - name: Remove the signing key
        run: shred -v -z -u -n 5 melange.rsa
        if: always()
