---
name: Checkmake Pull Requests

on:
  workflow_dispatch:
  pull_request:
    paths:
      - ".github/actions/**"
      - ".github/workflows/checkmake-*.yaml"
      - ".mise.*"
      - "tools/checkmake/**"
      - Makefile
      - melange.rsa.pub
      - scripts/**"

jobs:
  build:
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        arch: ["amd64"]
    services:
      docker:
        image: docker:dind
        options: --privileged --shm-size=2g
        # volumes:
        #   - /var/run/docker.sock:/var/run/docker.sock
    steps:
      # - name: Harden Runner
      #   uses: step-security/harden-runner@v2
      #   with:
      #     egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Dump the signing key
        run: if [ ! -f "melange.rsa" ]; then echo "${{ secrets.MELANGE_SIGNING_KEY }}" > melange.rsa; fi

      # - name: Install os deps
      #   run: sudo apt update -y && sudo apt install -y bubblewrap

      - name: Install mise
        uses: jdx/mise-action@v2
        with:
          version: 2024.11.4
      - name: Activate mise
        shell: sh
        run: echo 'eval "$(~/.local/share/mise/bin/mise activate bash)"' >> ~/.bashrc

      - name: Test build of new tool version
        uses: ./.github/actions/tool
        with:
          name: checkmake
          arch: ${{ matrix.arch }}
          publish: false

      - name: Remove the signing key
        run: shred -v -z -u -n 5 melange.rsa
        if: always()
