name: Diff
on:
  workflow_dispatch:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Generate config
        shell: sh
        run: make generate-config
      - name: Verify no changes are made
        shell: sh
        run: git diff --exit-code
