# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: Diff
permissions:
  contents: read
on:
  workflow_dispatch:
  pull_request:
jobs:
  diff:
    runs-on: ubuntu-24.04
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Install mise
        uses: jdx/mise-action@v2
        with:
          version: 2025.4.0
      - name: Activate mise
        shell: sh
        run: echo 'eval "$(~/.local/share/mise/bin/mise activate bash)"' >> ~/.bashrc
      - name: Make generate-config
        shell: sh
        run: make generate-config
      - name: Verify no changes are made
        shell: sh
        run: git diff --exit-code
