# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: Jsonlint
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/workflows/jsonlint.yaml
      - tools/jsonlint/**
      - .github/actions/**
      - .mise.*
      - Makefile
      - melange.rsa.pub
      - scripts/**
      - pages/**
      - '!pages/content'
  pull_request:
    paths:
      - .github/workflows/jsonlint.yaml
      - tools/jsonlint/**
      - .github/actions/**
      - .mise.*
      - Makefile
      - melange.rsa.pub
      - scripts/**
      - pages/**
      - '!pages/content'
jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      id-token: write
      packages: write
      pages: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Build image
        uses: ./.github/actions/image
        with:
          container_registry_password: ${{ secrets.CI_TOKEN }}
          melange_signing_key: ${{ secrets.MELANGE_SIGNING_KEY }}
          snyk_org: ${{ secrets.SNYK_ORG }}
          snyk_token: ${{ secrets.SNYK_TOKEN }}
          image_name: jsonlint
          publish: ${{ github.ref == 'refs/heads/main' && 'true' || 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
