# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: Yamlfmt
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - tools/yamlfmt/**
  pull_request:
    paths:
      - tools/yamlfmt/**
jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      id-token: write
      packages: write
      pages: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Determine image version
        shell: sh
        run: echo IMAGE_VERSION=$(scripts/image-version.sh yamlfmt) >> ${GITHUB_ENV}
      - name: Draft GitHub Release
        shell: sh
        run: make draft-gh-release IMAGE=yamlfmt VERSION=${{ env.IMAGE_VERSION }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image
        uses: ./.github/actions/image
        with:
          container_registry_password: ${{ secrets.CI_TOKEN }}
          melange_signing_key: ${{ secrets.MELANGE_SIGNING_KEY }}
          image_name: yamlfmt
          publish: ${{ github.ref == 'refs/heads/main' && 'true' || 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Scan image
        uses: ./.github/actions/scans
        with:
          container_registry_password: ${{ secrets.CI_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          snyk_org: ${{ secrets.SNYK_ORG }}
          snyk_token: ${{ secrets.SNYK_TOKEN }}
          image_name: yamlfmt
          publish: ${{ github.ref == 'refs/heads/main' && 'true' || 'false' }}
          pull_images: "false"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate pages
        uses: ./.github/actions/pages
        with:
          publish: ${{ github.ref == 'refs/heads/main' && 'true' || 'false' }}
          content_subject: yamlfmt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish GitHub Release
        shell: sh
        run: make publish-gh-release IMAGE=yamlfmt VERSION=${{ env.IMAGE_VERSION }}
        if: ${{ inputs.publish == 'true' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
