package:
  name: file-lint
  version: "0.8"
  epoch: 0
  description: cytopia/file-lint image.

  copyright:
    - license: MIT
      paths:
        - "*"
  dependencies:
    runtime: []

environment:
  contents:
    repositories:
      - https://dl-cdn.alpinelinux.org/alpine/v3.21/main
    packages:
      - apk-tools
      - busybox

pipeline:
  - name: Update registries
    runs: apk update
  - name: Clone cytopia's file-lint repository
    uses: git-checkout
    with:
      repository: https://github.com/cytopia/docker-file-lint
      destination: /tmp/docker-file-lint
      branch: master
      depth: "1"
  - name: Install file-lint
    runs: |
      mkdir -p ${{targets.destdir}}/usr/bin
      cp -r /tmp/docker-file-lint/Dockerfiles/data/* "${{targets.destdir}}/usr/bin"
